version: "3.3"
services:
  desconto-springboot:
    container_name: container-jdk11
    image: descontospringboot:v1.0
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile            
    ports:
      - 8081:8081
    environment:
      server.port: 8081
    volumes:
      - ./:/app    
    networks:
       - descontospringboot
      
networks:                     
    descontospringboot: